site_name: CS5250 Assignments (2025 Spring)
repo_url: https://github.com/nus-cs5250/25s
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.select
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - toc.integrate
markdown_extensions:
  - admonition
  - footnotes
  - mdx_truly_sane_lists
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - toc
extra_javascript:
  - javascripts/open_in_new_tab.js
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Assignment 1:
      - asg1/index.md
      - asg1/task-vm.md
      - asg1/task-kbuild.md
      - asg1/task-boot.md
  - Assignment 2:
      - asg2/index.md
      - asg2/task-browsing.md
      - asg2/task-gdb.md
      - asg2/task-module.md
      - asg2/task-syscall.md
  - Assignment 3:
      - asg3/index.md
      - asg3/task-kprobe.md
      - asg3/task-memhack.md
